// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcelToDatabase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240313110146_ABC")]
    partial class ABC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExcelToDatabase.Models.Pay_Deductions", b =>
                {
                    b.Property<int>("EmployeeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeCode"));

                    b.Property<decimal>("CcPension")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CcSocialSecurity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DdPension")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DdSocialSecurity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PayPoint")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeCode");

                    b.ToTable("Pay_Deduction");
                });
#pragma warning restore 612, 618
        }
    }
}
